CREATE TABLE PRODUCT (
	SKU INT NOT NULL PRIMARY KEY,
	NAME NCHAR(250) NOT NULL
);

CREATE TABLE WAREHOUSE (
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	SKU INT NOT NULL,
	LOCALITY VARCHAR(25) NOT NULL,
	QUANTITY INT NOT NULL,
	TYPE VARCHAR(50) NOT NULL
);

ALTER TABLE WAREHOUSE
   ADD CONSTRAINT FK_SKU FOREIGN KEY (SKU)
      REFERENCES PRODUCT (SKU)
      ON DELETE CASCADE
      ON UPDATE CASCADE;