INSERT INTO PRODUCT(SKU, NAME) VALUES(43264, 'L`Oréal Professionnel Expert Absolut Repair Cortex Lipidium - Máscara de Reconstrução 500g');

INSERT INTO WAREHOUSE(SKU, LOCALITY, QUANTITY, TYPE) VALUES (N'43264', 'SP', 12, 'ECOMMERCE');

INSERT INTO WAREHOUSE(SKU, LOCALITY, QUANTITY, TYPE) VALUES (N'43264', 'MOEMA', 12, 'PHYSICAL_STORE'); 